# Generated by Django 5.1 on 2024-08-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserves', '0002_alter_reserve_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
